### ISSUE TITLE
Base URL request problem

### ISSUE THREAD

**Issue by Chrapson** [Qqkyu/taboo-cards-api#3]
#### The base URL is the prefix for the API:

```http
   https://taboocardsapi.com/api/
```
#### Is returning:

`Error 301`

#### Sugested working frontend solution for request:
```http
   https://www.taboocardsapi.com/api/
```

or fix backend server error or change documentation.

**Comment by Qqkyu** [comment]
Hi, thanks for the info! I've changed the documentation and there is a correct base URL everywhere now - `https://www.taboocardsapi.com/api/`
